# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99a710641225da70f05d610e1f19440909f0f0a62908c65eb0910ebe644fb2edecff4ff07ac3035f9e06155bfb01501e61bc07c2fac458b7761c05f2e2d5023c

test:
  secret_key_base: 059ab594cbe040798235e3f9ede4a3b264855fcd72296201fdd09b9b13f653ed7ff5ea4307244666278cfe2bb45ed41db6f317da9b650d40cf43083088f69226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
